version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cinema-api:1.0
    container_name: cinema-api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - cinema-network

  db:
    image: postgres:15
    container_name: cinema-db
    restart: always
    environment:
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cinema-network

networks:
  cinema-network:

volumes:
  db_data: